coal_petrol_quiz={
	"info": {
		"name":    "",
		"main":    "Quiz Time! Click on 'Get Started' to begin quiz",
	},
	"questions": [
		{ // Question 1 - Multiple Choice, Single True Answer
			"q": "Why do oil and gas companies use hydrofracing'?",
			"a": [
				{"option": "to break up rock resulting in collapse and upward movement of oils and gas", "incorrect": false},
				{"option": "to de-pressurize sandstones to cause fluids to flow more efficiently", "incorrect": false},
				{"option": "to separate water from oil and gas, reducing the amount of water generated by a recovery well", "incorrect": false},
				{"option": "to crack open 'tight' rocks, increasing permeability and liberating gas and oil", "correct": true},
				{"option": "to pressurize rock zones and push oil and gas toward recovery wells", "incorrect": false}
			],
			"correct": "<p>Yes. Water mixed with chemicals and particles are quickly pumped into tight rocks to fracture them free trapped gas and oil.</p>",
			"incorrect": "<p>No. Want to try again?</p>"},		
		{ // Question 
			"q": "What is petrolium formed from ",
			"a": [
				{"option": "Milfoil", "incorrect": false},
				{"option": "Seaweed, like kelp", "incorrect": false},
				{"option": "Marine algae", "correct": true},
				{"option": "Land plants", "incorrect": false},
				{"option": "Dinosaur fat", "incorrect": false} // no comma here
			],
			"correct": "<p>Correct. Petrolium comes from sediments containg marine algea</p>",
			"incorrect": "<p>Not correct</p>" 
		},
		{ // Question 
			"q": "What environment produces deposits that may become coal?",
			"a": [
				{"option": "Whitewater rivers", "incorrect": false},
				{"option": "Deep and cold lakes", "incorrect": false},
				{"option": "Deep oceans", "incorrect": false},
				{"option": "Tropical wetlands", "correct": true},
				{"option": "Subartic upland spruce forests", "incorrect": false} // no comma here
			],
			"correct": "<p>Right, Coal deposits commonly form in tropical coastal wetland environments</p>",
			"incorrect": "<p>I'm sorry :-( ¿Do you want to try again?</p>" 
		},
		// { // Question
		// 	"q": "<img src='./quiz/textural_tri_low.png' height=300px /> What is the USDA texture (using the chart) for a sediment with 25% sand, 35% clay and 40% silt?",
		// 	"a": [
		// 		{"option": "silty sand", "incorrect": false},
		// 		{"option": "sandy loam",     "incorrect": false},
		// 		{"option": "clay",     "incorrect": false},
		// 		{"option": "loam",     "incorrect": false},
		// 		{"option": "clay loam", "correct": true} // no comma here
		// 	],
		// 	"correct": "<p>Nice! projecting the times for this grain size distribution falls within the clay loam field.</p>",
		// 	"incorrect": "<p><span>¡Muy malo! ¿Do you want to try again?</span></p>" 
		// },
		//]
		]
}

